---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cameran-lai
  namespace: traefik
spec:
  secretName: traefik-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "traefik.cameran-lai.com"
  dnsNames:
    - "traefik.cameran-lai.com"
