---
cert-manager:
  extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
    - --dns01-recursive-nameservers-only
  installCRDs: false
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
      - "9.9.9.9"
  podDnsPolicy: None
  prometheus:
    enabled: false
  startupapicheck:
    timeout: 5m
  webhook:
    validatingWebhookConfiguration:
      namespaceSelector:
        matchExpressions:
          - key: cert-manager.io/disable-validation
            operator: NotIn
            values:
              - 'true'
          - key: control-plane
            operator: NotIn
            values:
              - 'true'
