---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.30.5
        ports:
          - containerPort: 80
        # securityContext:
        #   runAsUser: 1001
        #   runAsGroup: 2000
        volumeMounts:
          - name: vault-volume
            mountPath: /data
      volumes:
        - name: vault-volume
          persistentVolumeClaim:
            claimName: vault-volume
