---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: vaultwarden
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-volume
  labels:
    app: vaultwarden
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/vaultwarden
