---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
          fsGroup: 1000
      containers:
        - name: komga
          image: {{.Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 25600
              name: http
          volumeMounts:
            - name: books
              mountPath: /books
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          env:
            - name: TZ
              value: America/New_York
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
        - name: browser
          image: filebrowser/filebrowser:v2.27.0
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: books
              mountPath: /srv
      restartPolicy: Always
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: books-volume
        - name: config
          persistentVolumeClaim:
            claimName: config-volume
        - name: data
          persistentVolumeClaim:
            claimName: data-volume
