---
apiVersion: v1
kind: Service
metadata:
  name: komga-service
spec:
  selector:
    app: komga
  ports:
    - protocol: TCP
      port: 80
      targetPort: 25600
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: browser-service
spec:
  selector:
    app: komga
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
