traefik:
  globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"

  logs:
    general:
      level: DEBUG

  ports:
    web:
      redirectTo:
        port: websecure
        priority: 10
    websecure:
      tls:
        enabled: true


  ingressRoute:
    dashboard:
      enabled: false
      # entryPoints:
      #   - websecure
      # matchRule: Host(`traefik.cameran-lai.com`) && PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      # middlewares:
      #   - name: traefik-dashboard-basicauth
      #     namespace: traefik

  rbac:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer
    spec:
      loadBalancerIP: 192.168.10.1
