traefik:
  globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"

  logs:
    general:
      level: DEBUG

  ports:
    web:
      redirectTo:
        port: websecure
        priority: 10
      nodePort: 30080
    websecure:
      tls:
        enabled: true
      nodePort: 30443


  ingressRoute:
    dashboard:
      enabled: false

  rbac:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer
    spec:
      loadBalancerIP: 192.168.68.49
