apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-basicauth
spec:
  basicAuth:
    secret: traefik-dashboard-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-dashboard-prefix
spec:
  redirectRegex:
    regex: ".*#"
    replacement: "/dashboard/#"
    permanent: true
