---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
        - name: kavita
          image: jvmilazz0/kavita:canary-0.7.14.11
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: manga
              mountPath: /manga
              readOnly: true
            - name: config
              mountPath: /kavita/config
          env:
            - name: TZ
              value: America/New_York
      restartPolicy: Always
      volumes:
        - name: manga
          hostPath:
            path: /kavita/manga
        - name: config
          hostPath:
            path: /kavita/config
