---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cameran-lai
spec:
  secretName: auth-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "auth.cameran-lai.com"
  dnsNames:
    - "auth.cameran-lai.com"
