---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
        - name: kavita
          image: {{.Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: manga
              mountPath: /manga
            - name: config
              mountPath: /kavita/config
          env:
            - name: TZ
              value: America/New_York
        - name: browser
          image: filebrowser/filebrowser:v2.27.0
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: manga
              mountPath: /srv
      restartPolicy: Always
      volumes:
        - name: manga
          persistentVolumeClaim:
            claimName: manga-volume
        - name: config
          persistentVolumeClaim:
            claimName: config-volume
