---
apiVersion: v1
kind: Service
metadata:
  name: kavita-service
spec:
  selector:
    app: kavita
  ports:
    - protocol: TCP
      port: 442
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: browser-service
spec:
  selector:
    app: kavita
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
