---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cameran-lai
spec:
  secretName: {{ .Values.name }}-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: {{ .Values.name }}.cameran-lai.com
  dnsNames:
    - {{ .Values.name }}.cameran-lai.com
