apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.name }}.cameran-lai.com`)
      {{- if .Values.authentik.enabled }}
      middlewares:
        - name: authentik
          namespace: traefik
      {{- end }}
      services:
        - name: {{ .Values.name }}-service
          port: {{ .Values.port }}
  tls:
    secretName: {{ .Values.name }}-cert
