---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CamSac/iaac-helm-charts
    path: charts/Application/kavita
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kavita
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
