---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CamSac/iaac-helm-charts
    path: charts/Application/komga
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
