crowdsec:
  container_runtime: containerd

  tls:
    enabled: true
    bouncer:
      reflector:
        namespaces: ["traefik"]

  agent:
    acquisition:
      - namespace: traefik
        podName: traefik-*
        program: traefik
    env:
      - name: PARSERS
        value: "crowdsecurity/cri-logs crowdsecurity/whitelists"
      - name: COLLECTIONS
        value: "crowdsecurity/linux crowdsecurity/traefik firix/authentik MariuszKociubinski/bitwarden Dominic-Wagner/vaultwarden crowdsecurity/whitelist-good-actors"
    persistentVolume:
      config:
        enabled: false
    image:
      pullPolicy: Always

  lapi:
    dashboard:
      enabled: false
      ingress:
        host: dashboard.local
        enabled: true
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 250m
        memory: 200Mi
    env:
      - name: DISABLE_ONLINE_API
        value: "false"
      - name: ENROLL_KEY
        value: "clufx5jnd000el508su78egd9"
      - name: ENROLL_INSTANCE_NAME
        value: "raspberry-pi"
      - name: ENROLL_TAGS
        value: "homelab"

  image:
    pullPolicy: Always
