---
name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            aksCluster=$(az keyvault secret show --vault-name AKSKeyVault-CamSac --name aksCluster --query value -o tsv)
            aksResourceGroup=$(az keyvault secret show --vault-name AKSKeyVault-CamSac --name aksResourceGroup --query value -o tsv)

      - uses: azure/aks-set-context@v4
        with:
          resource-group: $aksResourceGroup
          cluster-name: $aksCluster

      - run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm install opentelemetry-operator open-telemetry/opentelemetry-operator
